apps/semi_users/urls.py
from django.conf.urls import url,include
# from django.contrib import admin
from .import views

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name="index"),
    url(r'^new_product/$',views.new_product,name="new_product"),
    url(r'^show_product/(?P<id>\d+)$',views.show_product,name="show_product"),
    url(r'^edit_product/(?P<id>\d+)$',views.edit_product,name="edit_product"),
    url(r'^remove/(?P<id>\d+)$',views.remove,name="remove"),
    url(r'^goback$',views.goback,name="goback"),
    # url(r'^show/$',views.show,name="show"),
    # url(r'^edit/$',views.edit,name="edit"),
    # url(r'^remove/$',views.remove,name="remove")
]

apps/user_app/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
from .import views
urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^register$',views.register,name="register"),
    url(r'^login$',views.login,name="login"),
]

semirestful_users/urls.py
from django.conf.urls import url,include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^products/',include('apps.semi_users.urls',namespace="products")),
]

apps/semi_users/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class ProductManager(models.Manager):
    def add_product(self,params):
        self.create(name=params['name'],description=params['description'],price=params['price'])


class Product(models.Model):
    name=models.CharField(max_length=50)
    description=models.TextField(max_length=255)
    price=models.IntegerField()

    objects=ProductManager()

apps/user_app/models.py
from __future__ import unicode_literals

from django.db import models
import re
import bcrypt
# Create your models here.
class UserManager(models.Manager):
    def validate(self,user):
        name_regex = re.compile(r'^[a-zA-Z]+$')
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if len(user['fname'])<2 and not name_regex.match(user['fname']):
            print "false first_name"
            return{'error': "Invalid first_name!"}
        elif len(user['lname'])<2 and not name_regex.match(user['lname']):
            print "false last_name"
            return{'error': "Invalid last_name!"}
        elif not EMAIL_REGEX.match(user['email']):
            print "false email"
            return{'error': "Invalid Email Address!"}
        elif len(user['password']) <8:
            print "false password"
            return{'error':"too short password"}
        elif not user['cpassword'] == user['password']:
            # print user['password']
            # print user['cpassword']
            print "false confirm password"
            return {'error':"password and confirm password do not match"}
        else:
            print "true"
            # print user
            pass2=user['password']
            pass3=pass2.encode()
            hashed= bcrypt.hashpw(pass3,bcrypt.gensalt())
            # print hashed
            # pass1= bcrypt.hashpw(pass3,hashed)
            # print pass1
            User.objects.create( first_name=user['fname'],last_name=user['lname'],email=user['email'],Password=hashed)
            return {'user':user}
    def login(self,user):
        print user
        user_log=self.filter(email=user['email'])
        if user_log:
            print user_log
            pass2=user['Password']
            pass3=pass2.encode()
            if bcrypt.hashpw(pass3,user_log[0].Password.encode())== user_log[0].Password:
                return {'user':user_log[0]}
            # else:
        return{'error':"email or password failed"}


class User(models.Model):
    first_name= models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email= models.EmailField()
    Password= models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)



    objects=UserManager()

apps/semi_users/views.py
from django.shortcuts import render,redirect
from . models import Product
# Create your views here.
def index(request):
    context={
    'products':Product.objects.all()
    }
    return render(request,"semi_users/index.html",context)
# def show(request):
#     pass
# def Edit(request):
#     pass
# def remove(request):
#     pass
 # def add(request):
 #     return redirect('products:new')
def new_product(request):
     if request.method == "POST":
         print "add user"
         Product.objects.add_product(request.POST)
         return redirect('products:index')

     else:
         return render(request,"semi_users/new.html")
def goback(request):
    return redirect('products:index')
def show_product(request,id):
    context ={
    'products':Product.objects.get(id=id)
    }
    return render (request,"semi_users/show.html",context)
def edit_product(request,id):
    if request.method == "POST":
        print request.POST
        Product.objects.filter(id=id).update(name=request.POST['name'],description=request.POST['description'],price=request.POST['price'])
        return redirect('products:index')


    context ={
                'products':Product.objects.get(id=id)
                }
    return render (request,"semi_users/edit.html",context)
def remove(request,id):
    product=Product.objects.get(id=id)
    product.delete()
    return redirect('products:index')

apps/user_app/views.py
from django.shortcuts import render,redirect
from .models import User
# Create your views here.
def index(request):
    return render(request,"user_app/index.html")
def register(request):
    if request.method == "POST":
        user1={
        'fname':request.POST['first_name'],
        'lname':request.POST['last_name'],
        'email':request.POST['email'],
        'password':request.POST['Password'],
        'cpassword':request.POST['cpassword'],
        }
        user=User.objects.validate(user1)
        if 'error' in user:
            print user['error']
            context={
                'errors':user['error']
            }
            return render(request,"user_app/index.html",context)
        else:
            context={
            'user':user
            }
        return render(request,"user_app/success.html",context)
    # else:
    #     return redirect('/')
def login(request):
    if request.method == "POST":

        user=User.objects.login(request.POST)
        # print type(user)
        if 'error' in user:
            print user['error']
            context={
                'errors':user['error']
            }
            return render(request,"user_app/index.html",context)
        else:
            context ={
                'user2':user
                }
        return render(request,"user_app/success.html",context)

apps/semi_users/templates/semi_users/edit.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h3>welcome to edit</h3>
    <form  action="{% url 'products:edit_product' id=products.id %}" method="post">
      {% csrf_token %}
      Name: <input type="text" name="name" value={{products.name}}>
      Description: <textarea name="description" rows="8" cols="40"> {{products.description}}</textarea>
      Price: <input type="text" name="price"  value={{products.price}}>
      <input type="submit"  value="edit_product">
    </form>
      <a href="{% url 'products:show_product' id=products.id %}">show</a>
      <a href="{% url 'products:goback' %}">Go_Back</a>
  </body>
</html>

apps/semi_users/templates/semi_users/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h3>Products</h3>
    <table>
      <thead>
        <th>
          NAME
        </th>
        <th>
          description
        </th>
        <th>
          price
        </th>
        <th>
          Actions
        </th>
      </thead>
      <tbody>
        {% for product in products %}
        <tr>
          <td>
            {{product.name}}
          </td>
          <td>
            {{product.description}}
          </td>
          <td>
            {{product.price}}
          </td>
          <td>
            <a href="{% url 'products:show_product' id=product.id %}">show</a>
            <a href="{% url 'products:edit_product' id=product.id %}">Edit</a>
            <form  action="{% url 'products:remove' id=product.id %}" method="post">
              {% csrf_token %}
              <input type="submit"  value="Remove">
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

   <a href="{% url 'products:new_product' %}">Add a new product</a>

      </body>
</html>

apps/semi_users/templates/semi_users/new.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h3>Add a user</h3>
    <form  action="{% url 'products:new_product' %}" method="post">
      {% csrf_token %}
      Name: <input type="text" name="name">
      Description: <textarea name="description" rows="8" cols="40"></textarea>
      Price: <input type="text" name="price" >
      <input type="submit"  value="add_user">
    </form>
    <a href="{% url 'products:goback' %}">Go_Back</a>
  </body>
</html>

apps/semi_users/templates/semi_users/show.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h3>welcome to show</h3>
    <h3>
      Product {{products.id}}

    </h3>
    <p>
      Name: {{products.name}}
    </p>
    <p>
      Description:{{products.description}}
    </p>
    <p>
      Price:{{products.price}}
    </p>

    <p>
      <a href="{% url 'products:edit_product' id=products.id %}">Edit</a>
      <a href="{% url 'products:goback' %}">Go_Back</a>
    </p>
  </body>
</html>

apps/user_app/templates/user_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p>
      welcome
    </p>
    <h3>Register</h3>
    <form  action="{% url 'user:register' %}" method="post">
      {% csrf_token %}
      First_name<input type="text" name="first_name">
      Last_name <input type="text" name="last_name">
      Email <input type="text" name="email" >
      Password <input type="Password" name="Password" >
      Confirm Password: <input type="Password" name="cpassword">
      <input type="submit"  value="Register">
    </form>

    <p>
      {{errors}}
    </p>
    <h3>Login</h3>
    <form class="" action="{% url 'user:login' %}" method="post">
      {% csrf_token %}
      Email:<input type="text" name="email" >
      Password: <input type="password" name="Password" >
      <input type="submit" value="Login">
    </form>


  </body>
</html>

apps/user_app/templates/user_app/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome {{user.user.fname}}</h1>
  </body>
</html>
{{user2.user.first_name}}